version: '3'

services:
  postgres_dev:
    image: postgres:13
    container_name: postgres_dev
    env_file: .env
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '${DB_PORT}:5432'
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-q', '-d', '${DB_NAME}', '-U', '${DB_USER}', '-h', '${DB_HOST}' ]
      interval: 2s
      timeout: 2s
      retries: 100

  products_api:
    build: .
    container_name: products_api
    env_file: .env
    depends_on:
      - postgres_dev
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development

networks:
  default:
    driver: bridge